myproject/charts/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField


class ChartForm(FlaskForm):
    valuesType = SelectField('Choose your value:', choices=[('USDT', 'USDT'), ('PLN', 'PLN'), ('BTC', 'BTC'),('ALL','ALL')])
    token = SelectField('Choose your token:', choices=[])
    submit = SubmitField('refresh')

myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from filePath import DataFolder
from flask_bootstrap import Bootstrap
from myproject.db import CoinsDb

app = Flask(__name__)
Bootstrap(app)
app.config['SECRET_KEY'] = "mysecretkey"

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL','sqlite:///' + os.path.join(DataFolder, 'crypto_db'))
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

Migrate(app, db)

CurrentDb=CoinsDb()

from myproject.charts.views import charts_blueprints

app.register_blueprint(charts_blueprints, url_prefix='/charts')

myproject/charts/views.py
from flask import Blueprint, render_template, request
from myproject import CurrentDb
from myproject.graphs import get_profit, profit
from myproject.charts.forms import ChartForm
charts_blueprints = Blueprint('charts', __name__, template_folder="templates/charts")
coin_list = ["Total_balance"]



@charts_blueprints.route('/charts', methods=['GET', 'POST'])
def add():
    form = ChartForm()

    form.token.choices = [(coin, coin) for coin in coin_list]
    df = CurrentDb.get_table_df("Total_balance")
    valueType = "USDT"
    get_profit(df, valueType)

    if request.method == 'POST':
        df = CurrentDb.get_table_df(form.token.data)
        valueType = form.valuesType.data
        if valueType not in df.keys():
            valueType = "USDT"
        get_profit(df, valueType)



    return render_template('lineChart.html', form=form, x_val=df["data"].to_json(), y_val=df[valueType].to_json(),
                           profit=profit)


@charts_blueprints.route('/googlePie', methods=['GET', 'POST'])
def add3dPie():
    graphData=[]
    sampleCoin = ['Task', 'Hours per Day']
    graphData.append(sampleCoin)
    for coin in coin_list:
        df = CurrentDb.get_table_df(coin)
        get_profit(df, "USDT")
        if coin!="Total_balance":
            sampleCoin = []
            sampleCoin.append(coin)
            sampleCoin.append(profit["last_val"].__float__())
            graphData.append(sampleCoin)
    return render_template('googlePie.html',graphData=graphData )

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Binance account</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link rel="stylesheet" href='/static/css/sidenav.css'/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.bundle.js"></script>
    <!--    <script src="/assets/vendor/chart11.js/dist/Chart.extension.js"></script>-->
    <script type="text/javascript" src="/static/js/lineChart.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>

<body style=background-color:#152b35;" onload="runChart({{x_val}},{{y_val}})">

<nav class="navbar  navbar-expand-lg  navbar-dark bg-dark">

    <div class="navbar-nav  mx-auto">

        <a class='nav-item nav-link' href="{{url_for('home')}}">HOME</a>

        <a class='nav-item nav-link' href="{{url_for('charts.add')}}">CHARTS</a>

        <a class='nav-item nav-link' href="{{url_for('charts.add3dPie')}}">Google 3D Pie</a>
    </div>

</nav>


{% block content %}
{%endblock %}

</body>
</html>

myproject/templates/home.html
{%extends "base.html"%}


{%block content%}

<div class="jumbotron">

    <p>Home page</p>

</div>

{%endblock%}